#
# Summary: Default config for CGI directory
# Provides: Directory
# Provides: Directory-cgi
#

#
# "/var/www/cgi-bin" should be changed to whatever your ScriptAliased
# CGI directory exists, if you have that configured.
#
Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
Require all granted
