#
# Summary: proxy_module configure
# Provides: Extra
#

<IfModule proxy_module>
	<Proxy *>
		AddDefaultCharset off
		Require all denied
		#Require host .example.com
	</Proxy>

	# Enable/disable the handling of HTTP/1.1 "Via:" headers.
	# ("Full" adds the server version; "Block" removes all outgoing Via: headers)
	# Set to one of: Off | On | Full | Block

	ProxyVia On
</IfModule>
