#
# Summary: Distributed authoring and versioning (WebDAV)
# Provides: Extra
#

#
# Distributed authoring and versioning (WebDAV)
#
# Required modules: mod_dav, mod_dav_fs, mod_setenvif, mod_alias
#                   mod_auth_digest, mod_authn_file
#

# The following example gives DAV write access to a directory called
# "uploads" under the ServerRoot directory.
#
# The User/Group specified in httpd.conf needs to have write permissions
# on the directory where the DavLockDB is placed and on any directory where
# "Dav On" is specified.

<IfModule alias_module>
	Alias /uploads "/etc/httpd2/uploads"
</IfModule>

<IfModule dav_module>
	<Directory "/etc/httpd2/uploads">
		Dav On

		Require all granted

		AuthType Digest
		AuthName DAV-upload

		<IfModule authn_file_module>
			# You can use the htdigest program to create the password database:
			#   htdigest -c "/etc/httpd2/user.passwd" DAV-upload admin
			AuthUserFile "/etc/httpd2/user.passwd"
			AuthDigestProvider file
		</IfModule>

		# Allow universal read-access, but writes are restricted
		# to the admin user.
		<LimitExcept GET OPTIONS>
			require user admin
		</LimitExcept>
	</Directory>
</IfModule>

