#
# Summary: Icons for server-generated directory listings.
# Provides: Extra
#

#
# Required modules: mod_alias
#

<IfModule alias_module>
	# We include the /icons/ alias for FancyIndexed directory listings.  If
	# you do not use FancyIndexing, you may comment this out.
	#
	Alias /icons/ "/var/www/icons/"
</IfModule>

<Directory "/var/www/icons">
	Options Indexes MultiViews
	AllowOverride None
	Require all granted
</Directory>
